# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Contabilidade Pública
email: everton3x@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Artigos, papers, e material sobre Contabilidade Pública.
baseurl: "/contabilidadepublica" # the subpath of your site, e.g. /blog
url: "https://everton3x.github.io" # the base hostname & protocol for your site
twitter_username: everton3x
github_username:  everton3x

# Build settings
markdown: kramdown

destination: docs # necessário para o github reconhecer corretamente o site
timezone: America/Sao_Paulo
encoding: utf-8
