# SITE CONFIGURATION
baseurl: "/contabilidadepublica"
url: "https://everton3x.github.io"
title: Contabilidade Pública # site's title
description: "Artigos, papers e conteúdo sobre Contabilidade Pública." # used by search engines

timezone: America/Sao_Paulo
encoding: utf-8
destination: "docs"
defaults:
  -
    scope:
      path: ""
    values:
      author: "everton3x"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Contabilidade Pública # blog's title
  avatar: assets/img/caduceu.svg
  favicon: assets/favicon.ico
  gravatar: 0a175cf735e882a8c81d12d05952842c # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Textos, artigos e material sobre Contabilidade Pública.</p>
  header_text_feature_image: assets/img/pexels/banner.jpg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: everton3x@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "everton3x"
  flickr:
  gitlab:
  github: "everton3x"
  google_plus:
  instagram:
  keybase:
  linkedin:  https://www.linkedin.com/in/everton-da-rosa-65354371/ # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: everton3x # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: true
    tumblr: true
    pinterest: true
    pocket: true
    reddit: true
    linkedin: true
    wordpress: true
    email: true

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  special_page:
    search:
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true

  # Localization strings
  str_follow_on: "Siga-nos"
  str_rss_follow: "RSS feed"
  str_share_on: "Compartilhe"
  str_add_to: "Adicione para"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Próximo"
  str_previous_post: "Anterior"
  str_next_page: "Próximo"
  str_previous_page: "Anterior"
  str_continue_reading: "Continue lendo..."
  str_javascript_required_disqus: "Por favor, habilite o JavaScript pra ver comentários."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true


# PAGINATION
paginate: 10
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
